# Generated by Django 6.0.3 on 2026-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('INSPECTOR', 'Inspector'), ('CONTRATISTA', 'Empresa Contratista')], default='CONTRATISTA', max_length=20),
        ),
    ]
