# Generated by Django 6.0.3 on 2026-04-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acta', models.CharField(choices=[('ENTREGA_TERRENO', 'Entrega de Terreno'), ('RECEPCION_OBS', 'Recepción con Observaciones'), ('RECEPCION_OK', 'Recepción sin Observaciones')], max_length=30)),
                ('numero_acta', models.PositiveIntegerField()),
                ('fecha_acta', models.DateField()),
                ('titulo', models.CharField(max_length=255)),
                ('cuerpo_acta', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente por Firmar'), ('FIRMADA', 'Firmada')], default='PENDIENTE', max_length=20)),
                ('nombre_obra', models.CharField(max_length=255)),
                ('codigo_licitacion', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('rut_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_inspector', models.CharField(max_length=255)),
                ('ubicacion_obra', models.CharField(blank=True, max_length=255, null=True)),
                ('firma_inspector_texto', models.CharField(max_length=255)),
                ('firma_empresa_texto', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'ordering': ['-fecha_acta', '-id'],
                'unique_together': {('obra', 'numero_acta')},
            },
        ),
    ]
