# Generated by Django 6.0.3 on 2026-04-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mandante', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_mandante', models.ImageField(blank=True, null=True, upload_to='actas/logos/')),
            ],
            options={
                'verbose_name': 'Configuración de Actas',
                'verbose_name_plural': 'Configuración de Actas',
            },
        ),
    ]
