# Generated by Django 6.0.3 on 2026-04-25 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_configuracionacta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='fecha_firma_empresa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='fecha_firma_inspector',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='firmado_empresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acta',
            name='firmado_inspector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acta',
            name='usuario_firma_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_firmadas_como_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acta',
            name='usuario_firma_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_firmadas_como_inspector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente por Firmar'), ('PENDIENTE_EMPRESA', 'Pendiente Firma Empresa'), ('PENDIENTE_INSPECTOR', 'Pendiente Firma Inspector'), ('FIRMADA', 'Firmada')], default='PENDIENTE', max_length=30),
        ),
    ]
