# Generated by Django 6.0.3 on 2026-04-19 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaEstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('nombre_partida', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('porcentaje_avance_periodo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_avance_acumulado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='edp.estadopago')),
            ],
            options={
                'verbose_name': 'Partida Estado de Pago',
                'verbose_name_plural': 'Partidas Estado de Pago',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
