# Generated by Django 6.0.3 on 2026-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0002_partidaestadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopago',
            name='anticipo_descontado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='monto_pagado_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='saldo_restante_por_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
