# Generated by Django 6.0.3 on 2026-05-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0003_estadopago_anticipo_descontado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopago',
            name='estado',
            field=models.CharField(choices=[('EN_GESTION', 'En Gestión'), ('ENVIADO', 'Enviado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PAGADO', 'Pagado')], default='BORRADOR', max_length=20),
        ),
    ]
