# Generated by Django 6.0.3 on 2026-05-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0004_alter_estadopago_estado'),
        ('obras', '0003_alter_obra_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partidaestadopago',
            options={'ordering': ['item', 'id'], 'verbose_name': 'Partida Estado de Pago', 'verbose_name_plural': 'Partidas Estado de Pago'},
        ),
        migrations.AlterUniqueTogether(
            name='estadopago',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='partidaestadopago',
            name='orden',
        ),
        migrations.AddField(
            model_name='partidaestadopago',
            name='item',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partidaestadopago',
            name='tipo_fila',
            field=models.CharField(choices=[('TITULO', 'Título de Subpartida'), ('PARTIDA', 'Partida Valorizada')], default='PARTIDA', max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopago',
            name='estado',
            field=models.CharField(choices=[('EN_GESTION', 'En Gestión'), ('ENVIADO', 'Enviado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PAGADO', 'Pagado')], default='EN_GESTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='partidaestadopago',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='partidaestadopago',
            name='porcentaje_avance_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partidaestadopago',
            name='porcentaje_avance_periodo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partidaestadopago',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='partidaestadopago',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='estadopago',
            constraint=models.UniqueConstraint(fields=('obra', 'numero_estado_pago'), name='unique_numero_edp_por_obra', violation_error_message='Ya existe un Estado de Pago con ese número para la obra seleccionada.'),
        ),
        migrations.AddConstraint(
            model_name='partidaestadopago',
            constraint=models.UniqueConstraint(fields=('estado_pago', 'item'), name='unique_item_por_estado_pago', violation_error_message='Ya existe una fila con ese ítem en esta planilla de partidas.'),
        ),
    ]
