# Generated by Django 6.0.3 on 2026-05-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0005_alter_partidaestadopago_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopago',
            name='porcentaje_gastos_generales',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='porcentaje_utilidades',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
    ]
