# Generated by Django 6.0.3 on 2026-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0006_estadopago_porcentaje_gastos_generales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopago',
            name='porcentaje_anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='porcentaje_devolucion_anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='tiene_anticipo',
            field=models.BooleanField(default=False),
        ),
    ]
