# Generated by Django 6.0.3 on 2026-05-03 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0007_estadopago_porcentaje_anticipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopago',
            name='estado_firma',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente por Firmar'), ('PENDIENTE_EMPRESA', 'Pendiente Firma Empresa'), ('PENDIENTE_INSPECTOR', 'Pendiente Firma Inspector'), ('FIRMADA', 'Firmada')], default='PENDIENTE', max_length=30),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='fecha_firma_empresa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='fecha_firma_inspector',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='firma_empresa_texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='firma_inspector_texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='firmado_empresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='firmado_inspector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='usuario_firma_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edps_firmados_como_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estadopago',
            name='usuario_firma_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edps_firmados_como_inspector', to=settings.AUTH_USER_MODEL),
        ),
    ]
