# Generated by Django 6.0.3 on 2026-04-24 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet_identidad', models.FileField(blank=True, null=True, upload_to='trabajadores/carnet/')),
                ('certificado_antecedentes', models.FileField(blank=True, null=True, upload_to='trabajadores/antecedentes/')),
                ('contrato_trabajo', models.FileField(blank=True, null=True, upload_to='trabajadores/contratos/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='trabajadores.trabajador')),
            ],
            options={
                'verbose_name': 'Documento de Trabajador',
                'verbose_name_plural': 'Documentos de Trabajadores',
            },
        ),
    ]
