# Generated by Django 6.0.3 on 2026-04-18 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_garantia', models.CharField(choices=[('FIEL_CUMPLIMIENTO', 'Fiel Correcto Cumplimiento de Contrato'), ('RESPONSABILIDAD_CIVIL', 'Responsabilidad Civil'), ('ANTICIPO', 'Anticipo')], max_length=30)),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_termino_vigencia', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'ordering': ['fecha_termino_vigencia'],
            },
        ),
    ]
