# Generated by Django 6.0.3 on 2026-04-11 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('campus', models.CharField(choices=[('CAMPUS_1', 'Campus Central'), ('CAMPUS_2', 'Campus Norte'), ('CAMPUS_3', 'Campus Sur'), ('CAMPUS_4', 'Campus Poniente')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'Planificación'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada')], default='PLANIFICACION', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_como_empresa', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_como_inspector', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
