# Generated by Django 6.0.3 on 2026-04-26 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='rut_empresa',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato xx.xxx.xxx-x', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')]),
        ),
    ]
