# Generated by Django 6.0.3 on 2026-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_obra_rut_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('PLANIFICACION', 'Planificación'), ('EN_PROCESO', 'En Ejecución'), ('FINALIZADA', 'Finalizada')], default='PLANIFICACION', max_length=20),
        ),
    ]
