# Generated by Django 6.0.3 on 2026-04-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100, unique=True)),
                ('tipo_contrato', models.CharField(choices=[('PRIMITIVO', 'Primitivo'), ('ADENDUM', 'Adendum')], default='PRIMITIVO', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plazo_dias', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido')], default='VIGENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='obras.obra')),
            ],
        ),
    ]
