# Generated by Django 6.0.3 on 2026-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('obras', '0003_alter_obra_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(fields=('obra', 'numero_contrato'), name='unique_numero_contrato_por_obra'),
        ),
    ]
