# Generated by Django 6.0.3 on 2026-05-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contrato_options_and_more'),
        ('obras', '0003_alter_obra_estado'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='contrato',
            name='unique_numero_contrato_por_obra',
            constraint=models.UniqueConstraint(fields=('obra', 'numero_contrato'), name='unique_numero_contrato_por_obra', violation_error_message='Ya existe un contrato con ese número para la obra seleccionada.'),
        ),
    ]
